# Generated by Django 2.2 on 2021-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(default=0, upload_to='files/', verbose_name='изображения'),
            preserve_default=False,
        ),
    ]
