# Generated by Django 2.2 on 2021-01-15 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20210115_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='изображения'),
        ),
    ]
