# Generated by Django 2.2 on 2021-01-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
